import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppProvider } from "../context/AppContext";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import Sidebar from "../components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
         <body
           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
           <AppProvider>
             <div className="flex flex-col md:flex-row">
               <Sidebar />
   
               <main className="flex-1 md:ml-80">
                 <div className="glassmorphism main-content m-4 md:m-8 rounded-3xl p-6 md:p-8">
                   <Navigation />
   
                   {children}
   
                   <Footer />
                 </div>
               </main>
             </div>
           </AppProvider>
         </body>
       </html>
  );
}
